---
# tasks file for ec2-vpc-launch
 - name: install boto, boto3 & python3
   package:
           name: "{{ req_packages }}"
           state: present

 - name: create VPC
   ec2_vpc_net:
           name: "{{ vpc_name }}"
           cidr_block: "{{ vpc_cidr }}"
           profile: "{{ profile }}"
           region: "{{ region }}"
           state: present
   register: vpc_info

 - name: associate subnet to the VPC
   ec2_vpc_subnet:
           state: present
           vpc_id: "{{ vpc_info.vpc['id'] }}"
           region: "{{ region }}"
           profile: "{{ profile }}"
           cidr: "{{ subnet_cidr }}"
           map_public: yes
           resource_tags:
                   Name: "{{ subnet_name }}"
   register: subnet

 - name: create IGW
   ec2_vpc_igw:
           vpc_id: "{{ vpc_info.vpc['id'] }}"
           region: "{{ region }}"
           profile: "{{ profile }}"
           state: "present"
           tags:
                 Name: "{{ igw_name }}"
   register: igw

 - name: Route IGW
   ec2_vpc_route_table:
           vpc_id: "{{ vpc_info.vpc['id'] }}"
           region: "{{ region }}"
           profile: "{{ profile }}"
           subnets:
                 - "{{ subnet.subnet.id }}"
           routes:
                 - dest: 0.0.0.0/0
                   gateway_id: "{{ igw.gateway_id  }}"
           tags:
                 Name: "{{ route_name }}"
 - name: Create Security Group for webserver
   ec2_group:
           name: "{{ sg_name_wb }}"
           description: webserver
           vpc_id: "{{ vpc_info.vpc['id'] }}"
           profile: "{{ profile }}"
           region: "{{ region }}"
           rules:
              - proto: tcp
                ports:
                    - 80
                    - 22
                cidr_ip: 0.0.0.0/0
   register: security_group_wb
 - name: Create Security Group for LB
   ec2_group:
           name: "{{ sg_name_LB }}"
           description: security group for load balancer
           vpc_id: "{{ vpc_info.vpc['id'] }}"
           profile: "{{ profile }}"
           region: "{{ region }}"
           rules:
              - proto: tcp
                ports:
                    - 5000
                    - 22
                cidr_ip: 0.0.0.0/0
   register: security_group_LB

 - name: create a new ec2 key pair
   ec2_key:
           name: "{{ key_pair_name }}"
           region: "{{ region }}"
           profile: "{{ profile }}"
   register: keypair
 - name: Copy EC2 Private Key locally so it can be later on used to SSH into the instance
   copy: 
        content: "{{ keypair.key.private_key }}"
        dest: "{{ my_key_pair_dest }}"
        mode: 0600
   when: keypair.changed == true

 - name: "Launch EC2 instance for webserver"
   ec2:
           image: "{{ image_id }}"
           wait: yes
           instance_type: "{{ instance_type }}"
           region: "{{ region }}"
           profile: "{{ profile }}"
           group_id: "{{ security_group_wb.group_id }}"
           vpc_subnet_id: "{{ subnet.subnet.id }}"
           key_name: "{{ key_pair_name }}"
           instance_tags:
              "name": "webserver"
           count: 2
 - name: "Launch EC2 instance for LB" 
   ec2:
           image: "{{ image_id }}"
           wait: yes
           instance_type: "{{ instance_type }}"
           region: "{{ region }}"
           profile: "{{ profile }}"
           group_id: "{{ security_group_LB.group_id }}"
           vpc_subnet_id: "{{ subnet.subnet.id }}"
           key_name: "{{ key_pair_name }}"
           instance_tags:
              "name": "LB"
           
